version: "3"
services:
  client:
    build: ./client
    volumes:
      - build-volume:/build
  goclient:
    build: ./goclient
    ports:
      - "8080:8080"
    volumes:
      - build-volume:/build
  server:
    build: ./server
    ports:
      - "9000:9000"
  gateway:
    build: ./gateway
    ports:
      - "9090:9090"
volumes:
  build-volume:
