version: "3"
services:
  client:
    build: ./client
    volumes:
      - build-volume:/build
  proto:
    build: ./protozoaire
    volumes:
      - proto-volume:/proto
  goclient:
    build: ./goclient
    ports:
      - "8080:8080"
    volumes:
      - build-volume:/build
volumes:
  build-volume:
  proto-volume:
